"""Interface definitions for dependency injection"""

from typing import Protocol, Optional, List, Dict, Any
from PyQt5.QtCore import pyqtSignal

from .models import DataPoint, ScanParameters


class IMQTTClient(Protocol):
    """MQTT client interface"""
    
    connected: pyqtSignal
    position_data_received: pyqtSignal
    current_data_received: pyqtSignal
    
    def setup_mqtt(self, host: str, port: int) -> None: ...
    def connect_mqtt(self) -> None: ...
    def disconnect_mqtt(self) -> None: ...
    def send_command(self, command: str) -> None: ...
    
    @property
    def connected_status(self) -> bool: ...


class IDataProcessor(Protocol):
    """Data processor interface"""
    
    new_data_point: pyqtSignal
    statistics_update: pyqtSignal
    
    def process_position_data(self, payload: str) -> None: ...
    def process_current_data(self, payload: str) -> None: ...
    def emit_statistics(self) -> None: ...
    def set_storage(self, storage: 'IStorage') -> None: ...


class IStorage(Protocol):
    """Storage interface"""
    
    def create_scan_record(self, scan_params: ScanParameters, scan_name: str) -> int: ...
    def save_data_point(self, scan_id: int, data_point: DataPoint) -> None: ...
    def save_batch(self, scan_id: int, data_points: List[DataPoint]) -> None: ...
    def complete_scan(self, scan_id: int) -> None: ...
    def close(self) -> None: ...


class IImageReconstructor(Protocol):
    """Image reconstructor interface"""
    
    image_updated: pyqtSignal
    pixel_updated: pyqtSignal
    
    def initialize_scan(self, scan_params: ScanParameters) -> None: ...
    def add_data_point(self, data_point: DataPoint) -> None: ...
    def emit_full_image(self) -> None: ...
    def get_completion_percentage(self) -> float: ...
